#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from sintatica.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "sintatica.y"

#include <iostream>
#include <sstream>
#include <vector>
#include <stack>

#define YYSTYPE atributos

using namespace std;

typedef struct 
{
    string label;
    string traducao;
    string tipo;
} atributos; 

typedef struct
{
    string nomeVariavel;
    string tipoVariavel;
    string nomeOriginal;
    stack<int>escopo;

} TIPO_SIMBOLO; 

//GLOBAIS

vector<TIPO_SIMBOLO> tabelaSimbolos;
int numBloco;
stack<int>escopoAtual;
int yylex(void);
void yyerror(string);
string geraLabel();
void imprimirTabelaDeSimbolos();
atributos tipoID(atributos a, atributos b,atributos c, string tipo);
atributos converteTipo(atributos a, atributos b, atributos c, string caracter);
void insereTabelaDeSimbolos(atributos a,  string tipo);
void insereID(atributos a,  string tipo);

/*void printpilhasdeSimbolos()
{
    for(int i = 0; i < tabelaSimbolos.size(); i++)
    {
        cout << "\t" << tabelaSimbolos[i].escopo.top()<< " " <<tabelaSimbolos[i].nomeVariavel<<endl;
    }
} */



#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	TK_NUM	258
#define	TK_REAL	259
#define	TK_CHAR	260
#define	TK_CAST_INT	261
#define	TK_CAST_FLOAT	262
#define	TK_MA	263
#define	TK_ME	264
#define	TK_DF	265
#define	TK_IG	266
#define	TK_OU	267
#define	TK_NO	268
#define	TK_E	269
#define	TK_CONTINUE	270
#define	TK_BREAK	271
#define	TK_TIPO_STRING	272
#define	TK_STRING	273
#define	TK_MAIN	274
#define	TK_ID	275
#define	TK_TIPO_INT	276
#define	TK_TIPO_FLOAT	277
#define	TK_TIPO_BOOL	278
#define	TK_TIPO_CHAR	279
#define	TK_IF	280
#define	TK_ELSE	281
#define	TK_ELSE_IF	282
#define	TK_WHILE	283
#define	TK_INCREMENTO	284
#define	TK_DECREMENTO	285
#define	TK_FOR	286
#define	TK_FIM	287
#define	TK_ERROR	288


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int TK_NUM;
static const int TK_REAL;
static const int TK_CHAR;
static const int TK_CAST_INT;
static const int TK_CAST_FLOAT;
static const int TK_MA;
static const int TK_ME;
static const int TK_DF;
static const int TK_IG;
static const int TK_OU;
static const int TK_NO;
static const int TK_E;
static const int TK_CONTINUE;
static const int TK_BREAK;
static const int TK_TIPO_STRING;
static const int TK_STRING;
static const int TK_MAIN;
static const int TK_ID;
static const int TK_TIPO_INT;
static const int TK_TIPO_FLOAT;
static const int TK_TIPO_BOOL;
static const int TK_TIPO_CHAR;
static const int TK_IF;
static const int TK_ELSE;
static const int TK_ELSE_IF;
static const int TK_WHILE;
static const int TK_INCREMENTO;
static const int TK_DECREMENTO;
static const int TK_FOR;
static const int TK_FIM;
static const int TK_ERROR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,TK_NUM=258
	,TK_REAL=259
	,TK_CHAR=260
	,TK_CAST_INT=261
	,TK_CAST_FLOAT=262
	,TK_MA=263
	,TK_ME=264
	,TK_DF=265
	,TK_IG=266
	,TK_OU=267
	,TK_NO=268
	,TK_E=269
	,TK_CONTINUE=270
	,TK_BREAK=271
	,TK_TIPO_STRING=272
	,TK_STRING=273
	,TK_MAIN=274
	,TK_ID=275
	,TK_TIPO_INT=276
	,TK_TIPO_FLOAT=277
	,TK_TIPO_BOOL=278
	,TK_TIPO_CHAR=279
	,TK_IF=280
	,TK_ELSE=281
	,TK_ELSE_IF=282
	,TK_WHILE=283
	,TK_INCREMENTO=284
	,TK_DECREMENTO=285
	,TK_FOR=286
	,TK_FIM=287
	,TK_ERROR=288


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::TK_NUM=258;
const int YY_parse_CLASS::TK_REAL=259;
const int YY_parse_CLASS::TK_CHAR=260;
const int YY_parse_CLASS::TK_CAST_INT=261;
const int YY_parse_CLASS::TK_CAST_FLOAT=262;
const int YY_parse_CLASS::TK_MA=263;
const int YY_parse_CLASS::TK_ME=264;
const int YY_parse_CLASS::TK_DF=265;
const int YY_parse_CLASS::TK_IG=266;
const int YY_parse_CLASS::TK_OU=267;
const int YY_parse_CLASS::TK_NO=268;
const int YY_parse_CLASS::TK_E=269;
const int YY_parse_CLASS::TK_CONTINUE=270;
const int YY_parse_CLASS::TK_BREAK=271;
const int YY_parse_CLASS::TK_TIPO_STRING=272;
const int YY_parse_CLASS::TK_STRING=273;
const int YY_parse_CLASS::TK_MAIN=274;
const int YY_parse_CLASS::TK_ID=275;
const int YY_parse_CLASS::TK_TIPO_INT=276;
const int YY_parse_CLASS::TK_TIPO_FLOAT=277;
const int YY_parse_CLASS::TK_TIPO_BOOL=278;
const int YY_parse_CLASS::TK_TIPO_CHAR=279;
const int YY_parse_CLASS::TK_IF=280;
const int YY_parse_CLASS::TK_ELSE=281;
const int YY_parse_CLASS::TK_ELSE_IF=282;
const int YY_parse_CLASS::TK_WHILE=283;
const int YY_parse_CLASS::TK_INCREMENTO=284;
const int YY_parse_CLASS::TK_DECREMENTO=285;
const int YY_parse_CLASS::TK_FOR=286;
const int YY_parse_CLASS::TK_FIM=287;
const int YY_parse_CLASS::TK_ERROR=288;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		137
#define	YYFLAG		-32768
#define	YYNTBASE	46

#define YYTRANSLATE(x) ((unsigned)(x) <= 288 ? yytranslate[x] : 55)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    40,
    41,    38,    36,     2,    37,     2,    39,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    44,    35,
    45,    34,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    42,     2,    43,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     6,    12,    13,    14,    17,    18,    24,    30,    34,
    45,    60,    65,    70,    71,    74,    76,    78,    82,    86,
    90,    94,    98,   102,   106,   110,   114,   118,   122,   126,
   130,   134,   138,   142,   146,   150,   152,   154,   156,   159,
   162,   164,   166,   168,   172,   175,   178,   183,   188,   193,
   198
};

static const short yyrhs[] = {    21,
    19,    40,    41,    47,     0,    42,    48,    50,    49,    43,
     0,     0,     0,    53,    50,     0,     0,    25,    40,    54,
    41,    47,     0,    27,    40,    54,    41,    47,     0,    51,
    26,    47,     0,    28,    40,    54,    41,    42,    48,    50,
    52,    49,    43,     0,    31,    40,    54,    44,    54,    44,
    54,    41,    42,    48,    50,    52,    49,    43,     0,    16,
    44,    50,    52,     0,    15,    44,    50,    52,     0,     0,
    54,    44,     0,    47,     0,    51,     0,    21,    20,    44,
     0,    22,    20,    44,     0,    23,    20,    44,     0,    24,
    20,    44,     0,    17,    20,    44,     0,    54,    36,    54,
     0,    54,    37,    54,     0,    54,    38,    54,     0,    54,
    39,    54,     0,    54,    34,    54,     0,    54,    35,    54,
     0,    54,     8,    54,     0,    54,     9,    54,     0,    54,
    11,    54,     0,    54,    10,    54,     0,    54,    12,    54,
     0,    54,    14,    54,     0,    54,    13,    54,     0,     5,
     0,    23,     0,    18,     0,     6,    54,     0,     7,    54,
     0,     3,     0,     4,     0,    20,     0,    20,    45,    54,
     0,    20,    29,     0,    20,    30,     0,    21,    20,    45,
    54,     0,    24,    20,    45,    54,     0,    23,    20,    45,
    54,     0,    17,    20,    45,    54,     0,    22,    20,    45,
    54,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    67,    76,    82,    90,    98,   102,   108,   115,   123,   127,
   138,   147,   151,   156,   161,   162,   164,   166,   173,   180,
   187,   194,   203,   207,   211,   215,   219,   225,   230,   235,
   240,   245,   250,   258,   268,   278,   287,   296,   305,   318,
   331,   340,   349,   392,   444,   480,   515,   519,   523,   527,
   531
};

static const char * const yytname[] = {   "$","error","$illegal.","TK_NUM","TK_REAL",
"TK_CHAR","TK_CAST_INT","TK_CAST_FLOAT","TK_MA","TK_ME","TK_DF","TK_IG","TK_OU",
"TK_NO","TK_E","TK_CONTINUE","TK_BREAK","TK_TIPO_STRING","TK_STRING","TK_MAIN",
"TK_ID","TK_TIPO_INT","TK_TIPO_FLOAT","TK_TIPO_BOOL","TK_TIPO_CHAR","TK_IF",
"TK_ELSE","TK_ELSE_IF","TK_WHILE","TK_INCREMENTO","TK_DECREMENTO","TK_FOR","TK_FIM",
"TK_ERROR","'>'","'<'","'+'","'-'","'*'","'/'","'('","')'","'{'","'}'","';'",
"'='","S","BLOCO","INICIO","FIM","COMANDOS","CONDICAO","BREAK","COMANDO","E",
""
};
#endif

static const short yyr1[] = {     0,
    46,    47,    48,    49,    50,    50,    51,    51,    51,    51,
    51,    52,    52,    52,    53,    53,    53,    53,    53,    53,
    53,    53,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,    54,    54,    54,    54,    54,    54,    54,    54,
    54
};

static const short yyr2[] = {     0,
     5,     5,     0,     0,     2,     0,     5,     5,     3,    10,
    14,     4,     4,     0,     2,     1,     1,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     1,     1,     1,     2,     2,
     1,     1,     1,     3,     2,     2,     4,     4,     4,     4,
     4
};

static const short yydefact[] = {     0,
     0,     0,     0,     0,     3,     1,     6,    41,    42,    36,
     0,     0,     0,    38,    43,     0,     0,    37,     0,     0,
     0,     0,     0,    16,     4,    17,     6,     0,     0,     0,
     0,    37,     0,    39,    40,     0,    45,    46,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     5,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    15,     0,     0,     0,     0,     0,    22,
     0,    44,    18,     0,    19,     0,    20,     0,    21,     0,
     0,     0,     0,     0,     2,     9,    29,    30,    32,    31,
    33,    35,    34,    27,    28,    23,    24,    25,    26,    50,
    47,    51,    49,    48,     0,     0,     0,     0,     7,     8,
     3,     0,     6,     0,    14,     0,     0,     0,     4,     0,
     6,     6,     0,     3,    14,    14,    10,     6,    13,    12,
    14,     4,     0,    11,     0,     0,     0
};

static const short yydefgoto[] = {   135,
    24,     7,    48,    25,    26,   119,    27,    28
};

static const short yypact[] = {   -16,
     2,    -1,    17,    19,-32768,-32768,   108,-32768,-32768,-32768,
    71,    71,    39,-32768,   -27,    42,    44,    48,    50,    26,
    31,    32,    33,-32768,-32768,    53,   108,   109,    66,    67,
    76,    80,    81,   252,   252,   -28,-32768,-32768,    71,   -22,
   -20,   -18,   -15,    71,    71,    71,    71,    59,    19,-32768,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    71,    71,    71,-32768,    61,    62,    63,    79,    82,-32768,
    71,   252,-32768,    71,-32768,    71,-32768,    71,-32768,    71,
   194,   202,   210,   146,-32768,-32768,   -25,   -25,   -25,   -25,
    46,    46,    46,   -25,   -25,    -7,    -7,-32768,-32768,   252,
   252,   252,   252,   252,    19,    19,    74,    71,-32768,-32768,
-32768,   157,   108,    71,    22,   244,    60,    90,-32768,    95,
   108,   108,    97,-32768,    22,    22,-32768,   108,-32768,-32768,
    22,-32768,    98,-32768,   138,   142,-32768
};

static const short yypgoto[] = {-32768,
     4,  -105,  -112,   -23,-32768,  -116,-32768,   -11
};


#define	YYLAST		291


static const short yytable[] = {    34,
    35,    37,    38,    50,     1,   113,   123,     6,   129,   130,
    60,    61,    62,    63,   132,    70,    71,    39,   128,   133,
     2,    73,    74,    75,    76,    77,    78,    72,    79,    80,
    62,    63,    81,    82,    83,    84,   117,   118,     3,    87,
    88,    89,    90,    91,    92,    93,    94,    95,    96,    97,
    98,    99,    86,    51,    52,    53,    54,     4,    36,   100,
     5,    40,   101,    41,   102,    44,   103,    42,   104,    43,
    45,    46,    47,     8,     9,    10,    11,    12,    49,    58,
    59,    60,    61,    62,    63,    65,    66,    29,    14,   115,
    15,    30,    31,    32,    33,    67,   112,   125,   126,    68,
    69,    85,   116,   121,   131,    71,    74,    76,   109,   110,
     8,     9,    10,    11,    12,   111,    51,    52,    53,    54,
    55,    56,    57,    78,    13,    14,    80,    15,    16,    17,
    18,    19,    20,   122,    21,    22,   124,   136,    23,   127,
   134,   137,    58,    59,    60,    61,    62,    63,     0,     5,
     0,     0,    64,    51,    52,    53,    54,    55,    56,    57,
     0,     0,     0,     0,    51,    52,    53,    54,    55,    56,
    57,     0,     0,     0,     0,     0,     0,     0,     0,    58,
    59,    60,    61,    62,    63,     0,     0,     0,     0,   108,
    58,    59,    60,    61,    62,    63,     0,     0,     0,     0,
   114,    51,    52,    53,    54,    55,    56,    57,     0,    51,
    52,    53,    54,    55,    56,    57,     0,    51,    52,    53,
    54,    55,    56,    57,     0,     0,     0,    58,    59,    60,
    61,    62,    63,     0,   105,    58,    59,    60,    61,    62,
    63,     0,   106,    58,    59,    60,    61,    62,    63,     0,
   107,    51,    52,    53,    54,    55,    56,    57,     0,    51,
    52,    53,    54,    55,    56,    57,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    58,    59,    60,
    61,    62,    63,     0,   120,    58,    59,    60,    61,    62,
    63
};

static const short yycheck[] = {    11,
    12,    29,    30,    27,    21,   111,   119,     4,   125,   126,
    36,    37,    38,    39,   131,    44,    45,    45,   124,   132,
    19,    44,    45,    44,    45,    44,    45,    39,    44,    45,
    38,    39,    44,    45,    46,    47,    15,    16,    40,    51,
    52,    53,    54,    55,    56,    57,    58,    59,    60,    61,
    62,    63,    49,     8,     9,    10,    11,    41,    20,    71,
    42,    20,    74,    20,    76,    40,    78,    20,    80,    20,
    40,    40,    40,     3,     4,     5,     6,     7,    26,    34,
    35,    36,    37,    38,    39,    20,    20,    17,    18,   113,
    20,    21,    22,    23,    24,    20,   108,   121,   122,    20,
    20,    43,   114,    44,   128,    45,    45,    45,   105,   106,
     3,     4,     5,     6,     7,    42,     8,     9,    10,    11,
    12,    13,    14,    45,    17,    18,    45,    20,    21,    22,
    23,    24,    25,    44,    27,    28,    42,     0,    31,    43,
    43,     0,    34,    35,    36,    37,    38,    39,    -1,    42,
    -1,    -1,    44,     8,     9,    10,    11,    12,    13,    14,
    -1,    -1,    -1,    -1,     8,     9,    10,    11,    12,    13,
    14,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    34,
    35,    36,    37,    38,    39,    -1,    -1,    -1,    -1,    44,
    34,    35,    36,    37,    38,    39,    -1,    -1,    -1,    -1,
    44,     8,     9,    10,    11,    12,    13,    14,    -1,     8,
     9,    10,    11,    12,    13,    14,    -1,     8,     9,    10,
    11,    12,    13,    14,    -1,    -1,    -1,    34,    35,    36,
    37,    38,    39,    -1,    41,    34,    35,    36,    37,    38,
    39,    -1,    41,    34,    35,    36,    37,    38,    39,    -1,
    41,     8,     9,    10,    11,    12,    13,    14,    -1,     8,
     9,    10,    11,    12,    13,    14,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    34,    35,    36,
    37,    38,    39,    -1,    41,    34,    35,    36,    37,    38,
    39
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 68 "sintatica.y"
{
                cout << "\n\nXxx---COMPILADOR J.M.B---xxX\n" << "#include <iostream>\n#include<string.h>\n#include<stdio.h>\nint main(void)\n{\n";
                imprimirTabelaDeSimbolos();
                cout << yyvsp[0].traducao << "\treturn 0;\n\n}" << endl;
                //printpilhasdeSimbolos();
            ;
    break;}
case 2:
#line 77 "sintatica.y"
{
                yyval.traducao = yyvsp[-2].traducao ;
                
            ;
    break;}
case 3:
#line 83 "sintatica.y"
{
                //Diferenciar o número dos blocos
                numBloco++;
                escopoAtual.push(numBloco);
                yyval.traducao = "";
            ;
    break;}
case 4:
#line 91 "sintatica.y"
{
                escopoAtual.pop();
                yyval.traducao = "";
            ;
    break;}
case 5:
#line 99 "sintatica.y"
{
                yyval.traducao = yyvsp[-1].traducao + yyvsp[0].traducao;
            ;
    break;}
case 6:
#line 103 "sintatica.y"
{
                yyval.traducao = "";
            ;
    break;}
case 7:
#line 109 "sintatica.y"
{
                yyval.label = geraLabel();
                insereTabelaDeSimbolos(yyval,"int");
                yyval.traducao =yyvsp[-2].traducao + "\t" + yyval.label + " != " + yyvsp[-2].label + ";\n"; 
                yyval.traducao+="\tIF(" + yyval.label + ") GOTO FIM_IF " + to_string(numBloco-1) + ";\n" + yyvsp[0].traducao + "\tFIM_IF "+ to_string(numBloco-1) +";\n\n";
            ;
    break;}
case 8:
#line 116 "sintatica.y"
{
                yyval.label = geraLabel();
                insereTabelaDeSimbolos(yyval,"int");
                yyval.traducao = yyvsp[-2].traducao + "\t" + yyval.label + " != " + yyvsp[-2].label + ";\n"; 
                yyval.traducao+="\tIF("+ yyval.label + ") GOTO FIM_ELSE_IF" + to_string(numBloco-1) + ";\n" + yyvsp[0].traducao + "\tFIM_ELSE_IF" + to_string(numBloco-1) + ";\n\n";
            ;
    break;}
case 9:
#line 124 "sintatica.y"
{
                yyval.traducao= yyvsp[-2].traducao + "\tIF(!" + yyvsp[-2].label + ") GOTO FIM_ELSE " + to_string(numBloco-1) + ";\n" + yyvsp[0].traducao + "\tFIM_ELSE " + to_string(numBloco-1) + ";\n\n";
            ;
    break;}
case 10:
#line 129 "sintatica.y"
{
                
                escopoAtual.push(numBloco);
                yyval.label = geraLabel();
                string tempVar = geraLabel();
                insereTabelaDeSimbolos(yyval,"int");
                yyval.traducao ="INICIO_WHILE "+ to_string(numBloco-1) +":\n"+ yyvsp[-7].traducao + "\t" + yyval.label + " = " + yyvsp[-7].label + ";\n\t" + tempVar + " = !" + yyval.label + "\n"; 
                yyval.traducao+="\tIF(" + tempVar + ") GOTO FIM_WHILE "+ to_string(numBloco-1)  +";\n" + yyvsp[-3].traducao + yyvsp[-2].traducao + "\tGOTO INICIO_WHILE "+ to_string(numBloco-1) +"\n" +"FIM_WHILE " + to_string(numBloco-1) + ";\n\n";
            ;
    break;}
case 11:
#line 139 "sintatica.y"
{
                yyval.label = geraLabel();
                string tempVar = geraLabel();
                insereTabelaDeSimbolos(yyval,"int");
                yyval.traducao ="INICIO_FOR "+ to_string(numBloco-1) +":\n"+ yyvsp[-11].traducao + yyvsp[-9].traducao + "\t" + yyval.label + " = " + yyvsp[-9].label + ";\n\t" + tempVar + " = !" + yyval.label + "\n"; 
                yyval.traducao+="\tIF(" + tempVar + ") GOTO FIM_FOR "+ to_string(numBloco-1) +";\n" + yyvsp[-3].traducao + yyvsp[-2].traducao + yyvsp[-7].traducao +"\tGOTO INICIO_FOR "+ to_string(numBloco-1) +"\n" +"FIM_FOR " + to_string(numBloco-1) + ";\n\n";
            ;
    break;}
case 12:
#line 148 "sintatica.y"
{
                yyval.traducao = "\tGOTO BLOCO " + to_string(numBloco-1) + ";\n" + yyvsp[-1].traducao + yyvsp[0].traducao;
            ;
    break;}
case 13:
#line 153 "sintatica.y"
{
                yyval.traducao = "\tGOTO BLOCO " + to_string(numBloco-1) + ";\n" + yyvsp[-1].traducao + yyvsp[0].traducao;
            ;
    break;}
case 14:
#line 157 "sintatica.y"
{
                yyval.traducao = "";
            ;
    break;}
case 18:
#line 167 "sintatica.y"
{
                insereID(yyvsp[-1],"int");

                yyval.traducao = "";
                yyval.label = ""; 
            ;
    break;}
case 19:
#line 174 "sintatica.y"
{
                insereID(yyvsp[-1],"float");

                yyval.traducao = "";
                yyval.label = ""; 
            ;
    break;}
case 20:
#line 181 "sintatica.y"
{
                insereID(yyvsp[-1],"bool");

                yyval.traducao = "";
                yyval.label = ""; 
            ;
    break;}
case 21:
#line 188 "sintatica.y"
{
                insereID(yyvsp[-1],"char");

                yyval.traducao = "";
                yyval.label = ""; 
            ;
    break;}
case 22:
#line 195 "sintatica.y"
{
                insereID(yyvsp[-1], "string");

                yyval.traducao = "";
                yyval.label = "";
            ;
    break;}
case 23:
#line 204 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"+");
            ;
    break;}
case 24:
#line 208 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"-");
            ;
    break;}
case 25:
#line 212 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"*");
            ;
    break;}
case 26:
#line 216 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"/");
            ;
    break;}
case 27:
#line 220 "sintatica.y"
{
               yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,">");
               //Convertendo o tipo para Bool nos relacionais para poder fazer comparação com os lógicos
               yyval.tipo = "bool";
            ;
    break;}
case 28:
#line 226 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"<");
                yyval.tipo = "bool";
            ;
    break;}
case 29:
#line 231 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,">=");
                yyval.tipo = "bool";
            ;
    break;}
case 30:
#line 236 "sintatica.y"
{
               yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"<=");
               yyval.tipo = "bool";
            ;
    break;}
case 31:
#line 241 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval,"==");
                yyval.tipo = "bool";
            ;
    break;}
case 32:
#line 246 "sintatica.y"
{
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval," != ");
                yyval.tipo = "bool";
            ;
    break;}
case 33:
#line 251 "sintatica.y"
{
                if (yyvsp[-2].tipo != "bool" || yyvsp[0].tipo != "bool"){
                    yyerror("ERRO! Operação inválida");
                }

                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval," || ");
            ;
    break;}
case 34:
#line 259 "sintatica.y"
{
                if (yyvsp[-2].tipo != "bool"){
                    yyerror("ERRO! Operação inválida");
                }
                if (yyvsp[0].tipo != "bool"){
                    yyerror("ERRO! Operação inválida");
                }
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval," && ");
            ;
    break;}
case 35:
#line 269 "sintatica.y"
{
                if (yyvsp[-2].tipo != "bool"){
                    yyerror("ERRO! Operação inválida");
                }
                if (yyvsp[0].tipo != "bool"){
                    yyerror("ERRO! Operação inválida");
                }
                yyval = converteTipo(yyvsp[-2], yyvsp[0],yyval," ! ");
            ;
    break;}
case 36:
#line 279 "sintatica.y"
{
                yyval.tipo = "char";
                yyval.label = geraLabel();
                yyval.traducao = "\t" + yyval.label + " = "  + yyvsp[0].traducao + ";\n";

                // Adicionar variável temporária na tabela de símbolos
                insereTabelaDeSimbolos(yyval,"char");
            ;
    break;}
case 37:
#line 288 "sintatica.y"
{
                yyval.tipo = "bool";
                yyval.label = geraLabel();
                yyval.traducao = "\t" + yyval.label + " = "  + yyvsp[0].traducao + ";\n";

                // Adicionar variável temporária na tabela de símbolos
                insereTabelaDeSimbolos(yyval,"int");
            ;
    break;}
case 38:
#line 297 "sintatica.y"
{
                yyval.tipo = "string";
                yyval.label = geraLabel();
                yyval.traducao = "\t" + yyval.label + " = "  + yyvsp[0].traducao + ";\n";

                // Adicionar variável temporária na tabela de símbolos
                insereTabelaDeSimbolos(yyval,"string");
            ;
    break;}
case 39:
#line 306 "sintatica.y"
{
                if(yyvsp[0].tipo == "float")
                {
                    yyvsp[0].label = "(int)" + yyvsp[0].label;
                    yyvsp[0].tipo = "int";
                }
                yyval.label = geraLabel();
                yyval.tipo = "int";
                yyval.traducao = yyvsp[0].traducao + "\t" + yyval.label + " = " + yyvsp[0].label + ";\n";

                insereTabelaDeSimbolos(yyval,"int");
            ;
    break;}
case 40:
#line 319 "sintatica.y"
{
                if(yyvsp[0].tipo == "int")
                {
                    yyvsp[0].label = "(float)" + yyvsp[0].label;
                    yyvsp[0].tipo = "float";
                }
                yyval.label = geraLabel();
                yyval.tipo = "float";
                yyval.traducao = yyvsp[0].traducao + "\t" + yyval.label + " = " + yyvsp[0].label+ ";\n";

                insereTabelaDeSimbolos(yyval,"float");
            ;
    break;}
case 41:
#line 332 "sintatica.y"
{
                yyval.tipo = "int";
                yyval.label = geraLabel();
                yyval.traducao = "\t" + yyval.label + " = "  + yyvsp[0].traducao + ";\n";

                // Adicionar variável temporária na tabela de símbolos
                insereTabelaDeSimbolos(yyval,"int");
            ;
    break;}
case 42:
#line 341 "sintatica.y"
{
                yyval.tipo = "float";
                yyval.label = geraLabel();
                yyval.traducao = "\t" + yyval.label + " = "  + yyvsp[0].traducao + ";\n";

                // Adicionar variável temporária na tabela de símbolos
                insereTabelaDeSimbolos(yyval,"float");
            ;
    break;}
case 43:
#line 350 "sintatica.y"
{
                if(yyvsp[0].label == "true" || yyvsp[0].label == "false"){
                    yyval.label = geraLabel();
                    insereTabelaDeSimbolos(yyval,"int");
                    yyval.tipo = "bool";
                    yyval.traducao = "\t" + yyval.label + " = " + yyvsp[0].label + ";\n";
                }
                else{
                    bool encontrei = false; 
                    TIPO_SIMBOLO variavel; 
                    for (int i = tabelaSimbolos.size();i>=0; i--){
                    if((tabelaSimbolos[i].nomeOriginal == yyvsp[0].label && tabelaSimbolos[i].escopo.size() == escopoAtual.size() && tabelaSimbolos[i].escopo.top()== escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                        break;
                    }
                    else if((tabelaSimbolos[i].nomeOriginal == yyvsp[0].label && tabelaSimbolos[i].escopo.size() <= escopoAtual.size() && tabelaSimbolos[i].escopo.top()<= escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                    }
                }
                    if(!encontrei){
                        if(yyvsp[0].label == "true" || yyvsp[0].label == "false"){
                            yyval.tipo = "bool";
                        } 
                    else{
                        yyerror("Variavel não declarada!");}
                    }

                    yyval.tipo = variavel.tipoVariavel; 
                    yyval.label = geraLabel();
                    yyval.traducao = "\t" + yyval.label + " = " + variavel.nomeVariavel + ";\n";

                    // Adicionar variável temporária na tabela de símbolos
                    TIPO_SIMBOLO temp;
                    temp.nomeVariavel = yyval.label;
                    temp.nomeOriginal = yyvsp[0].label;
                    temp.escopo = escopoAtual;
                    temp.tipoVariavel = variavel.tipoVariavel;
                    tabelaSimbolos.push_back(temp);
                }
            ;
    break;}
case 44:
#line 393 "sintatica.y"
{
                bool encontrei = false; 
                TIPO_SIMBOLO variavel; 
                for (int i = tabelaSimbolos.size();i>=0; i--){
                    if((tabelaSimbolos[i].nomeOriginal == yyvsp[-2].label && tabelaSimbolos[i].escopo.size() == escopoAtual.size() && tabelaSimbolos[i].escopo.top()== escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                        break;
                    }
                    else if((tabelaSimbolos[i].nomeOriginal == yyvsp[-2].label && tabelaSimbolos[i].escopo.size() <= escopoAtual.size() && tabelaSimbolos[i].escopo.top()<= escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                    }
                }
                if(!encontrei){
                    yyerror("Variavel não declarada!");
                }

                //Retornar erro se tentar atribuir bool ou char com outro tipo
                if(variavel.tipoVariavel=="bool" && yyvsp[0].tipo !="bool" || variavel.tipoVariavel=="char" && yyvsp[0].tipo !="char" || yyvsp[0].tipo=="bool" && variavel.tipoVariavel !="bool" || yyvsp[0].tipo=="char" && variavel.tipoVariavel !="char"){
                    yyerror("Atribuição inválida!!!");
                }
                if(variavel.tipoVariavel=="int" && yyvsp[0].tipo =="float")
		        {
                    string tempVar = geraLabel();
		        	yyval.label = geraLabel();
                    yyval.traducao = yyvsp[0].traducao + "\t" + tempVar + " = (int)"+ yyvsp[0].label + ";\n\t" + variavel.nomeVariavel + " = " + tempVar + ";\n";

                    TIPO_SIMBOLO temp;
                    temp.nomeVariavel = tempVar;
                    temp.escopo = escopoAtual;
                    temp.tipoVariavel = variavel.tipoVariavel;
                    tabelaSimbolos.push_back(temp);
		        }
                else if(variavel.tipoVariavel=="float" && yyvsp[0].tipo =="int")
		        {
                    string tempVar = geraLabel();
		        	yyval.label = geraLabel();
                    yyval.traducao = yyvsp[0].traducao + "\t" + tempVar + " = (float)"+yyvsp[0].label + ";\n\t" + variavel.nomeVariavel + " = " + tempVar + ";\n";

                    TIPO_SIMBOLO temp;
                    temp.nomeVariavel = tempVar;
                    temp.escopo = escopoAtual;
                    temp.tipoVariavel = variavel.tipoVariavel;
                    tabelaSimbolos.push_back(temp);
		        }
                else{
                yyval.label = geraLabel();
                yyval.traducao = yyvsp[0].traducao + "\t" + variavel.nomeVariavel + " = " + yyvsp[0].label + ";\n";}

            ;
    break;}
case 45:
#line 445 "sintatica.y"
{
            
                bool encontrei = false; 
                TIPO_SIMBOLO variavel; 
                for (int i = tabelaSimbolos.size();i>=0; i--){
                    if((tabelaSimbolos[i].nomeOriginal == yyvsp[-1].label && tabelaSimbolos[i].escopo.size() == escopoAtual.size() && tabelaSimbolos[i].escopo.top()== escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                        break;
                    }
                    else if((tabelaSimbolos[i].nomeOriginal == yyvsp[-1].label && tabelaSimbolos[i].escopo.size() <= escopoAtual.size() && tabelaSimbolos[i].escopo.top()<= escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                    }
                }
                if(!encontrei){
                    if(yyvsp[-1].label == "true" || yyvsp[-1].label == "false"){
                        yyval.tipo = "bool";
                    } 
                else{
                    yyerror("Variavel não declarada!");}
                }
                yyval.tipo = variavel.tipoVariavel; 
                yyval.label = geraLabel();
                string um = geraLabel();
                yyval.traducao = "\t"+ um + " = 1\n\t" + yyval.label + " = " + variavel.nomeVariavel + "+" + um+ ";\n";
                // Adicionar variável temporária na tabela de símbolos
                TIPO_SIMBOLO temp;
                temp.nomeVariavel = yyval.label + ";\n\tint " + um;
                temp.nomeOriginal = yyvsp[-1].label;
                temp.escopo = escopoAtual;
                temp.tipoVariavel = variavel.tipoVariavel;
                tabelaSimbolos.push_back(temp);
                
            ;
    break;}
case 46:
#line 481 "sintatica.y"
{
                
                bool encontrei = false; 
                TIPO_SIMBOLO variavel; 
                for (int i = tabelaSimbolos.size();i>=0; i--){
                    if((tabelaSimbolos[i].nomeOriginal == yyvsp[-1].label && tabelaSimbolos[i].escopo.size() == escopoAtual.size() && tabelaSimbolos[i].escopo.top()== escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                        break;
                    }
                    else if((tabelaSimbolos[i].nomeOriginal == yyvsp[-1].label && tabelaSimbolos[i].escopo.size() <= escopoAtual.size() && tabelaSimbolos[i].escopo.top()<= escopoAtual.top())){
                        variavel = tabelaSimbolos[i];
                        encontrei = true;
                    }
                }
                if(!encontrei){
                    if(yyvsp[-1].label == "true" || yyvsp[-1].label == "false"){
                        yyval.tipo = "bool";
                    } 
                else{
                    yyerror("Variavel não declarada!");}
                }
                yyval.tipo = variavel.tipoVariavel; 
                yyval.label = geraLabel();
                string um = geraLabel();
                yyval.traducao = "\t"+ um + " = 1\n\t" + yyval.label + " = " + variavel.nomeVariavel + "-" + um+ ";\n";
                // Adicionar variável temporária na tabela de símbolos
                TIPO_SIMBOLO temp;
                temp.nomeVariavel = yyval.label + ";\n\tint " + um;
                temp.nomeOriginal = yyvsp[-1].label;
                temp.escopo = escopoAtual;
                temp.tipoVariavel = variavel.tipoVariavel;
                tabelaSimbolos.push_back(temp);
            ;
    break;}
case 47:
#line 516 "sintatica.y"
{
                yyval = tipoID(yyvsp[-2], yyvsp[0],yyval,"int");
            ;
    break;}
case 48:
#line 520 "sintatica.y"
{
                yyval = tipoID(yyvsp[-2], yyvsp[0],yyval,"char");
            ;
    break;}
case 49:
#line 524 "sintatica.y"
{
                yyval = tipoID(yyvsp[-2], yyvsp[0],yyval,"bool");
            ;
    break;}
case 50:
#line 528 "sintatica.y"
{
                yyval = tipoID(yyvsp[-2], yyvsp[0],yyval,"string");
            ;
    break;}
case 51:
#line 532 "sintatica.y"
{
                yyval = tipoID(yyvsp[-2], yyvsp[0],yyval,"float");
            ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 537 "sintatica.y"


#include "lex.yy.c"

int yyparse();

string geraLabel()
{
    static int i = 1;

    stringstream ss;
    ss << "T" << i++;

    return ss.str();
}

int main(int argc, char* argv[])
{
    numBloco = 0;
    escopoAtual.push(numBloco);
    yyparse();

    return 0;
}

void yyerror(string MSG)
{
    cout << MSG << endl;
    exit (0);
}               

void insereTabelaDeSimbolos(atributos a,string tipo){
    TIPO_SIMBOLO temp;
    temp.nomeVariavel = a.label;
    temp.tipoVariavel = tipo;
    temp.escopo = escopoAtual;
    tabelaSimbolos.push_back(temp);  
};

//Inserindo os tokens de ID na tabela de símbolos
void insereID(atributos a,string tipo){
    TIPO_SIMBOLO temp;
    temp.nomeVariavel = geraLabel();
    temp.escopo = escopoAtual;
    temp.nomeOriginal = a.label;
    temp.tipoVariavel = tipo; 
    
    for(int i = 0; i < tabelaSimbolos.size(); i++)
	{
		if(tabelaSimbolos[i].nomeOriginal == temp.nomeOriginal && tabelaSimbolos[i].escopo.top() == escopoAtual.top())
		{
			yyerror("Variavel já declarada!");
		}
	}
    tabelaSimbolos.push_back(temp);
};

atributos converteTipo(atributos a, atributos b,atributos c, string caracter){
    //Condições para converter de Int para Float
    if (a.tipo == "char" || b.tipo == "char") {
        yyerror("Erro. Operação inválida!");
    }
    if (a.tipo == "int" && b.tipo == "float") {
        string tempVar = geraLabel(); // Variável temporária para armazenar a conversão
        c.label = geraLabel();
        c.tipo = "float";
        c.traducao = a.traducao +  b.traducao + "\t" + tempVar + " = (float)" + a.label + ";\n";
        c.traducao += "\t" + c.label + " = " + b.label + caracter + tempVar + ";\n";
        
        // Atualizar tipo da temporária com base nos tipos dos operandos
        TIPO_SIMBOLO temp;
        temp.nomeVariavel = tempVar + ";\n\t"+ "int" + " " + c.label;
        temp.escopo = escopoAtual;
        temp.tipoVariavel = "float";
        tabelaSimbolos.push_back(temp);
    } 
    
    else if (a.tipo == "float" && b.tipo == "int") {
        string tempVar = geraLabel(); // Variável temporária para armazenar a conversão
        c.label = geraLabel();
        c.tipo = "float";
        c.traducao =a.traducao +  b.traducao + "\t" + tempVar + " = (float)" + b.label + ";\n";
        c.traducao += "\t" + c.label + " = " + a.label + caracter + tempVar + ";\n";
        // Atualizar tipo da temporária com base nos tipos dos operandos
        TIPO_SIMBOLO temp;
        temp.nomeVariavel = tempVar + ";\n\t"+ "int" + " " + c.label;
        temp.escopo = escopoAtual;
        temp.tipoVariavel = "float";
        tabelaSimbolos.push_back(temp);
    } 
    
    else {
        
        c.label = geraLabel();
        c.tipo = a.tipo;
        c.traducao = a.traducao + b.traducao + "\t" + c.label + 
            " = " + a.label + caracter + b.label + ";\n";
        // Atualizar tipo da temporária com base nos tipos dos operandos
        TIPO_SIMBOLO temp;
        temp.nomeVariavel = c.label;
        temp.escopo = escopoAtual;
        temp.tipoVariavel = "int";
        tabelaSimbolos.push_back(temp);
    }
    return c;
}

atributos tipoID(atributos a, atributos b,atributos c, string tipo){
    // Adicionar variável temporária na tabela de símbolos
    TIPO_SIMBOLO temp;
    temp.nomeVariavel = geraLabel();
    temp.escopo = escopoAtual;
    temp.nomeOriginal = a.label;
    temp.tipoVariavel = tipo;
        
     for(int i = 0; i < tabelaSimbolos.size(); i++)
	{
		if(tabelaSimbolos[i].nomeOriginal == temp.nomeOriginal && tabelaSimbolos[i].escopo.top() == escopoAtual.top())
		{
			yyerror("Variavel já declarada!");
		}
	}
    tabelaSimbolos.push_back(temp);
    //Retornar erro se tentar atribuir bool ou char com outro tipo
    if(temp.tipoVariavel=="bool" && b.tipo !="bool" || temp.tipoVariavel=="char" && b.tipo !="char" || b.tipo=="bool" && temp.tipoVariavel !="bool" || b.tipo=="char" && temp.tipoVariavel !="char"){
        yyerror("Atribuição inválida!!!");
    }

    //Conversão int p Float 
    if(temp.tipoVariavel=="int" && b.tipo =="float")
	{
        string tempVar = geraLabel();
		c.label = geraLabel();
        c.traducao = b.traducao + "\t" + tempVar + " = (int)"+b.label + ";\n\t" + temp.nomeVariavel + " = " + tempVar + ";\n";
        TIPO_SIMBOLO temp;
        temp.nomeVariavel = tempVar;
        temp.escopo = escopoAtual;
        temp.tipoVariavel = "int";
        tabelaSimbolos.push_back(temp);
	}
    //Conversão de Float p Int
    else if(temp.tipoVariavel=="float" && b.tipo =="int")
	{
        string tempVar = geraLabel();
		c.label = geraLabel();
        c.traducao = b.traducao + "\t" + tempVar + " = (float)"+b.label + ";\n\t" + temp.nomeVariavel + " = " + tempVar + ";\n";
        TIPO_SIMBOLO temp;
        temp.nomeVariavel = tempVar;
        temp.escopo = escopoAtual;
        temp.tipoVariavel = "float";
        tabelaSimbolos.push_back(temp);
	}
    else{
        c.tipo = temp.tipoVariavel; // Usar o tipo da variável original
        a.label = temp.nomeOriginal;
        c.traducao = b.traducao + "\t" + temp.nomeVariavel + " = " + b.label + ";\n";
    }
    return c;

}

void imprimirTabelaDeSimbolos()
{
    for(TIPO_SIMBOLO simbolo: tabelaSimbolos){
        cout<<"\t"+simbolo.tipoVariavel+" "+simbolo.nomeVariavel + ";" <<endl;
    }

}